spring:
  application:
    name: monitor-client
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.36.161:3306/monitor?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: ToBridges2020@mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/